import Head from "next/head";
import Image from "next/image";
import Navbar from "./Navbar";
import Link from "next/link";

import styles from '../styles/Home.module.css';

export default function Home() {

    const createHandler = (e: any) => {
        e.preventDefault();

        fetch('https://us-central1-teen-app-d6280.cloudfunctions.net/newTask' ,{
            method: "POST",
            headers: {
                "Content-Type":"application/json"
            },
            body: JSON.stringify({message:"Hello World!"})
        }).then(res => {
            console.log(res.body);
            return res.json()
        }).then(res => {
            console.log(res);
            
        }).catch(err => {
            console.log(err);
            
        })

    }

    return (
        <>
            <Head>
                <title>Home</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header>
                <Navbar />
            </header>
            <main>
                <button onClick={createHandler}>asd</button>
            </main>
            {/* <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer> */}
        </>
    )
}