import Head from "next/head";
import Navbar from "./Navbar";
import styles from '../styles/Home.module.css';
import TaskCreator from "./tasks/task-creator";
export default function Home() {
    return (
        <>
            <Head>
                <title>Home</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header>
                <Navbar />
            </header>
            <main>
                Hello World!
            </main>
            <footer className={styles.footer}>
                
                <TaskCreator/>
            </footer>
        </>
    )
}