import Head from "next/head";
import Tasks from "./Tasks";

export default function TodayTasks() {
    return (
        <>
            <Head>
                <title>Home</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Tasks />
        </>
    )
}