import Head from "next/head";
import Navbar from "./Navbar";
import Tasks from "./Tasks";
import Aside from "./Aside";

import styles from '../styles/Home.module.css';

export default function TodayTasks() {
    return (
        <>
            <Head>
                <title>Home</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header>
                <Navbar />
            </header>
            <main className={styles.main}>
                    <Tasks />
                    <Aside />
            </main>
        </>
    )
}